name: webdav_client
description: A simple WebDAV client that supports some common methods.

version: 1.1.8
homepage: https://github.com/flymzero/webdav_client

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  dio: ^4.0.6
  xml: ^6.1.0
  convert: ^3.0.2

dev_dependencies:
  test: '>=1.0.0 <2.0.0'
