name: webdav_client
description: A dart WebDAV client library
version: 0.0.1
author: flyzero
homepage: https://github.com/flymzero/webdav_client

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  crypto: ^2.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter