name: webdav_client
description: A dart WebDAV client library, use dio as http client. * support Basic/Digest authentication * common settings * read dir * make dir * delete * rename * copy * download file * upload file * cancel request 

version: 0.0.2
homepage: https://github.com/flymzero/webdav_client

environment:
  sdk: ">=2.10.0 <3.0.0"

dependencies:
  dio: ^3.0.10
  xml: ^4.5.1
  meta: ^1.2.3
  convert: ^2.1.1

dev_dependencies:
  test: '>=1.0.0 <2.0.0'