name: webdav_client
description: A dart WebDAV client library
version: 0.0.1
author: flyzero
homepage: https://github.com/flymzero/webdav_client

environment:
  sdk: ">=2.10.0 <3.0.0"

dependencies:
  xml: ^4.5.1
  intl: ^0.16.1

dev_dependencies:
  test: '>=1.0.0 <2.0.0'